const movieCategory = {
  popular: "popular",
  top_rated: "top_rated",
  upcoming: "upcoming",
};

const movieGenreIds = {
  Action: 28,
  Adventure: 12,
  Animation: 16,
  Comedy: 35,
  Crime: 80,
  Documentary: 99,
  Drama: 18,
  Family: 10751,
  Fantasy: 14,
  History: 36,
  Horror: 27,
  Music: 10402,
  Mystery: 9648,
  Romance: 10749,
  "Science Fiction": 878,
  "TV Movie": 10770,
  Thriller: 53,
  War: 10752,
  Western: 37,
};

const movieLanguageTags = {
  Bislama: "bi",
  Czech: "cs",
  Bashkir: "ba",
  Avestan: "ae",
  Avaric: "av",
  German: "de",
  Maltese: "mt",
  Oromo: "om",
  "Raeto-Romance": "rm",
  Somali: "so",
  Tsonga: "ts",
  Vietnamese: "vi",
  Guarani: "gn",
  Igbo: "ig",
  Italian: "it",
  Kikuyu: "ki",
  Kurdish: "ku",
  Latin: "la",
  Lingala: "ln",
  Letzeburgesch: "lb",
  "Chichewa; Nyanja": "ny",
  Polish: "pl",
  Sinhalese: "si",
  Tonga: "to",
  Azerbaijani: "az",
  Chechen: "ce",
  Slavic: "cu",
  Danish: "da",
  Herero: "hz",
  Interlingue: "ie",
  Kinyarwanda: "rw",
  Maori: "mi",
  Norwegian: "no",
  Pali: "pi",
  Slovak: "sk",
  "Northern Sami": "se",
  Samoan: "sm",
  Ukrainian: "uk",
  English: "en",
  Aymara: "ay",
  Catalan: "ca",
  Esperanto: "eo",
  Hausa: "ha",
  "Hiri Motu": "ho",
  Hungarian: "hu",
  Ido: "io",
  Yi: "ii",
  Kannada: "kn",
  Komi: "kv",
  Limburgish: "li",
  Ojibwa: "oj",
  Russian: "ru",
  Serbian: "sr",
  Swedish: "sv",
  Tahitian: "ty",
  Zulu: "zu",
  Georgian: "ka",
  Chamorro: "ch",
  Belarusian: "be",
  Breton: "br",
  Cornish: "kw",
  Finnish: "fi",
  "Serbo-Croatian": "sh",
  "Norwegian Nynorsk": "nn",
  Tatar: "tt",
  Tajik: "tg",
  Volapük: "vo",
  Pushto: "ps",
  Macedonian: "mk",
  French: "fr",
  Bambara: "bm",
  Basque: "eu",
  Fijian: "fj",
  Indonesian: "id",
  Malagasy: "mg",
  Nauru: "na",
  "No Language": "xx",
  Quechua: "qu",
  Albanian: "sq",
  Tigrinya: "ti",
  Twi: "tw",
  Walloon: "wa",
  Abkhazian: "ab",
  Bosnian: "bs",
  Afrikaans: "af",
  Aragonese: "an",
  Frisian: "fy",
  Gujarati: "gu",
  Inupiaq: "ik",
  Japanese: "ja",
  Korean: "ko",
  Ganda: "lg",
  Dutch: "nl",
  "Ossetian; Ossetic": "os",
  Greek: "el",
  Bengali: "bn",
  Cree: "cr",
  Khmer: "km",
  Lao: "lo",
  Ndebele: "nr",
  Nepali: "ne",
  Sardinian: "sc",
  Swahili: "sw",
  Tagalog: "tl",
  Urdu: "ur",
  Ewe: "ee",
  Afar: "aa",
  Corsican: "co",
  Estonian: "et",
  Icelandic: "is",
  Kashmiri: "ks",
  Kanuri: "kr",
  Kirghiz: "ky",
  Kuanyama: "kj",
  Oriya: "or",
  Wolof: "wo",
  Zhuang: "za",
  Arabic: "ar",
  Chuvash: "cv",
  Faroese: "fo",
  Croatian: "hr",
  Malay: "ms",
  "Norwegian Bokmål": "nb",
  Rundi: "rn",
  Shona: "sn",
  Sotho: "st",
  Turkish: "tr",
  Amharic: "am",
  Persian: "fa",
  Armenian: "hy",
  Punjabi: "pa",
  Assamese: "as",
  Interlingua: "ia",
  Latvian: "lv",
  "Luba-Katanga": "lu",
  Marathi: "mr",
  Mongolian: "mn",
  Portuguese: "pt",
  Thai: "th",
  Turkmen: "tk",
  Venda: "ve",
  Divehi: "dv",
  Manx: "gv",
  Kalaallisut: "kl",
  Kazakh: "kk",
  Lithuanian: "lt",
  Burmese: "my",
  Slovenian: "sl",
  Sindhi: "sd",
  Cantonese: "cn",
  Hindi: "hi",
  Welsh: "cy",
  "Haitian; Haitian Creole": "ht",
  Inuktitut: "iu",
  Javanese: "jv",
  Marshall: "mh",
  Sanskrit: "sa",
  Swati: "ss",
  Telugu: "te",
  Kongo: "kg",
  Malayalam: "ml",
  Uzbek: "uz",
  Sango: "sg",
  Xhosa: "xh",
  Spanish: "es",
  Sundanese: "su",
  Uighur: "ug",
  Yiddish: "yi",
  Yoruba: "yo",
  Mandarin: "zh",
  Hebrew: "he",
  Tibetan: "bo",
  Akan: "ak",
  Moldavian: "mo",
  Ndonga: "ng",
  Dzongkha: "dz",
  Fulah: "ff",
  Gaelic: "gd",
  Irish: "ga",
  Galician: "gl",
  Navajo: "nv",
  Occitan: "oc",
  Romanian: "ro",
  Tamil: "ta",
  Tswana: "tn",
  Bulgarian: "bg",
};

const backdropPath = (imgEndpoint) =>
  `https://image.tmdb.org/t/p/original${imgEndpoint}`;

const posterPath = (imgEndpoint) =>
  `https://image.tmdb.org/t/p/w500${imgEndpoint}`;

const youtubePath = (videoId) =>
  `https://www.youtube.com/embed/${videoId}?controls=0`;

const tmdbConfigs = {
  movieCategory,
  movieGenreIds,
  movieLanguageTags,
  backdropPath,
  posterPath,
  youtubePath,
};

export default tmdbConfigs;
